name: Go Sample CI pipeline definition

on: 
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Trigger Google Cloud Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        token_format: 'access_token'
        workload_identity_provider: projects/888836520522/locations/global/workloadIdentityPools/development-identity-pool/providers/github-identity-pool
        service_account: github-service-account@daniel-playground-365018.iam.gserviceaccount.com

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Use gcloud INFO
      run: 'gcloud info'

    - name: Start Google Cloud Build trigger
      run: |
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        gcloud beta builds triggers run ${{ steps.auth.outputs.access_token }} --tag=${{ github.event.release.tag_name }}