name: Go Sample CI pipeline definition

on: 
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        token_format: 'access_token'
        workload_identity_provider: https://iam.googleapis.com/projects/888836520522/locations/global/workloadIdentityPools/development-identity-pool/providers/github-identity-pool
        service_account: github-service-account@daniel-playground-365018.iam.gserviceaccount.com